[ package ]
name = "skydotenv"
version = "1.0.0"
edition = "2024"

[ dependencies ]
eframe = "0.27"
egui = "0.27"
walkdir = "2"
ignore = "0.4"
bsky-sdk = "0.1"
atrium-api = "0.1"
tokio = {version = "1", features = ["full"]}
dotenv = "0.15"
chrono = {version = "0.4", features = ["serde"]}